# Generated by Django 2.1.7 on 2019-04-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100, verbose_name='订单号')),
                ('waiter_phone', models.CharField(max_length=11, verbose_name='回收人员手机号')),
                ('customer_phone', models.CharField(max_length=11, verbose_name='社区用户手机号')),
                ('customer_address', models.CharField(max_length=200, verbose_name='社区人员地址')),
                ('total_money', models.FloatField(verbose_name='总金额')),
                ('commodities_desc', models.TextField(verbose_name='废品描述')),
                ('status', models.IntegerField(choices=[(1, '处理中'), (2, '已支付')], default=1, verbose_name='订单状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='下单时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
        migrations.CreateModel(
            name='PayMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=11, verbose_name='顾客')),
                ('money', models.FloatField(verbose_name='转账金额')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='转账时间')),
            ],
            options={
                'verbose_name': '转账历史记录',
                'verbose_name_plural': '转账历史记录',
            },
        ),
        migrations.CreateModel(
            name='SMSMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scrap_user_phone', models.CharField(max_length=11, verbose_name='回收人员手机号')),
                ('sent_time', models.DateTimeField(auto_now_add=True, verbose_name='短信发送时间')),
            ],
            options={
                'verbose_name': '短信发送历史记录',
                'verbose_name_plural': '短信发送历史记录',
            },
        ),
    ]
